const e=(name,sets,reps,rest,type,muscles,cues)=>({name,sets,reps,rest,type,muscles,cues});
export const foundationRoutines=[
{day:'Monday',short:'Upper A',title:'Upper body foundations',focus:'Chest · back · shoulders',time:45,category:'STRENGTH / UPPER',description:'Build a strong foundation. Controlled reps, confident movement.',exercises:[e('Dumbbell bench press',3,'8–12',90,'bench','Chest · triceps',['Plant your feet and keep your shoulder blades against the bench.','Lower dumbbells beside your chest with elbows at about 45°.','Press upward without bouncing or locking your elbows hard.']),e('Seated cable row',3,'10–12',90,'row','Back · biceps',['Sit tall with a neutral spine and softly bent knees.','Pull handles toward your lower ribs; keep elbows close.','Return slowly without rounding your back.']),e('Dumbbell shoulder press',2,'8–12',90,'press','Shoulders · triceps',['Sit against a backrest; brace your abdomen.','Start dumbbells beside shoulders and press overhead.','Keep ribs down and lower with control.']),e('Lat pulldown',3,'10–12',90,'pull','Back · biceps',['Keep your thighs under the pad and chest tall.','Pull the bar toward your upper chest, never behind your head.','Return slowly; avoid swinging.']),e('Dumbbell curl',2,'10–15',60,'curl','Biceps',['Stand tall with elbows at your sides.','Curl the weights without swinging your torso.','Lower slowly through a comfortable range.'])]},
{day:'Tuesday',short:'Lower A',title:'Strength from the ground up',focus:'Quads · glutes · core',time:45,category:'STRENGTH / LOWER',description:'A steady lower-body session. Make every rep intentional.',exercises:[e('Goblet squat',3,'8–12',90,'squat','Quads · glutes',['Hold one dumbbell close to your chest.','Sit down between your hips; knees track over toes.','Keep heels grounded and stand with control.']),e('Dumbbell Romanian deadlift',3,'8–12',90,'hinge','Hamstrings · glutes',['Keep a soft bend in your knees and weights near your thighs.','Push hips back with a neutral spine until you feel hamstrings stretch.','Stand by bringing hips forward; avoid leaning back.']),e('Reverse lunge',2,'8 / side',90,'lunge','Quads · glutes',['Step backward and keep your front foot planted.','Lower both knees through a comfortable range.','Push through the front foot to return; alternate sides.']),e('Standing calf raise',3,'12–15',60,'calf','Calves',['Use a wall or rack for balance.','Rise onto the balls of your feet.','Pause at the top and slowly lower your heels.']),e('Forearm plank',3,'20–30s',60,'plank','Core',['Place elbows under shoulders.','Keep your body in a straight line and breathe steadily.','End the hold before your lower back sags.'])]},
{day:'Wednesday',short:'Cardio',title:'Find your easy rhythm',focus:'Cardio · mobility',time:40,category:'CONDITIONING / EASY',description:'Move at a pace where you can still hold a conversation.',exercises:[e('Brisk treadmill walk',1,'30 min',0,'walk','Aerobic fitness',['Start with 5 easy minutes included in your 30-minute walk.','Increase pace until breathing is faster but talking stays comfortable.','Finish with a few easy minutes.']),e('Standing hip flexor stretch',2,'30s / side',15,'lunge','Hip mobility',['Take a split stance and gently tuck your pelvis.','Shift forward until you feel a mild stretch at the front of the back hip.','Breathe; avoid arching your lower back.']),e('Standing chest opener',2,'30s',15,'stretch','Chest mobility',['Stand tall and lightly clasp your hands behind you.','Gently open your chest without forcing shoulders back.','Keep ribs down and breathe normally.'])]},
{day:'Thursday',short:'Upper B',title:'A stronger kind of balance',focus:'Back · chest · arms',time:45,category:'STRENGTH / UPPER',description:'Your second upper day. Smooth movement beats heavy weight.',exercises:[e('Incline dumbbell press',3,'8–12',90,'incline','Upper chest · triceps',['Set the bench to a low incline, about 30°.','Keep shoulder blades against the bench.','Lower weights beside the chest and press upward.']),e('Single-arm dumbbell row',3,'10 / side',90,'onerow','Back · biceps',['Support one hand on a bench and hinge at your hips.','Pull the dumbbell toward your hip with your elbow close.','Lower slowly; keep your torso from rotating.']),e('Dumbbell lateral raise',2,'12–15',60,'raise','Shoulders',['Use light dumbbells and softly bent elbows.','Raise arms out to the sides up to shoulder height.','Lower slowly; avoid shrugging or swinging.']),e('Cable triceps pushdown',2,'10–15',60,'pushdown','Triceps',['Keep elbows tucked at your sides and shoulders relaxed.','Straighten arms to move the handle downward.','Return slowly without moving your upper arms.']),e('Dumbbell hammer curl',2,'10–15',60,'curl','Biceps · forearms',['Keep palms facing inward throughout the movement.','Curl with elbows close to your sides.','Lower with control without swinging.'])]},
{day:'Friday',short:'Lower B',title:'Build your engine',focus:'Glutes · hamstrings · core',time:45,category:'STRENGTH / LOWER',description:'Finish the lifting week with steady, purposeful reps.',exercises:[e('Dumbbell Romanian deadlift',3,'8–12',90,'hinge','Hamstrings · glutes',['Soften knees and keep weights close to legs.','Hinge hips backward with a neutral spine.','Return to standing by driving hips forward.']),e('Goblet squat',3,'10–12',90,'squat','Quads · glutes',['Hold the weight close to your chest.','Keep feet planted as you sit down between your hips.','Stand up smoothly with knees tracking over toes.']),e('Glute bridge',3,'12–15',60,'bridge','Glutes',['Lie on your back, feet planted and knees bent.','Lift hips by squeezing glutes, keeping ribs down.','Pause, then lower slowly without overextending your back.']),e('Standing calf raise',2,'12–15',60,'calf','Calves',['Hold a support for balance.','Rise onto your toes and pause.','Lower slowly, keeping movement comfortable.']),e('Dead bug',2,'8 / side',60,'deadbug','Core',['Lie on your back with arms up and knees at 90°.','Extend opposite arm and leg while keeping lower back gently grounded.','Return and alternate; use a smaller range if your back arches.'])]},
{day:'Saturday',short:'Move',title:'Move a little. Feel a lot.',focus:'Cardio · full-body mobility',time:40,category:'CONDITIONING / EASY',description:'Choose your pace and enjoy the movement. No rush today.',exercises:[e('Brisk outdoor or treadmill walk',1,'30 min',0,'walk','Aerobic fitness',['Begin slowly and build to a comfortable brisk pace.','Keep your shoulders relaxed and look ahead.','Use the talk test: you should still be able to speak in sentences.']),e('Bodyweight squat',2,'10',30,'squat','Hip · ankle mobility',['Stand with feet around shoulder width.','Sit down to a comfortable depth with heels planted.','Use a stable support if balance is difficult.']),e('Standing chest opener',2,'30s',15,'stretch','Shoulder mobility',['Stand tall with hands gently clasped behind you.','Open your chest gently without forcing the stretch.','Relax and breathe.'])]},
{day:'Sunday',short:'Recover',title:'Recovery is part of the work',focus:'Rest · gentle movement',time:15,category:'RECOVERY / REST',description:'Take the day off lifting. A gentle walk is entirely optional.',exercises:[e('Optional easy walk',1,'10 min',0,'walk','Gentle movement',['Walk at an easy, relaxed pace.','Let your breathing stay comfortable.','Skip this if you would prefer a complete rest day.']),e('Gentle standing side stretch',2,'20s / side',15,'stretch','Gentle mobility',['Stand comfortably and reach one arm overhead.','Lean a little to the opposite side without twisting.','Keep the stretch mild and breathe.'])]}
];

const equipmentByName={
 'Dumbbell bench press':['Flat bench + dumbbells','Per dumbbell'],
 'Seated cable row':['Low cable row station + close-grip handle','Selected stack weight'],
 'Dumbbell shoulder press':['Upright bench + dumbbells','Per dumbbell'],
 'Lat pulldown':['High pulley + pulldown bar','Selected stack weight'],
 'Dumbbell curl':['Dumbbells','Per dumbbell'],
 'Goblet squat':['One dumbbell','Dumbbell weight'],
 'Dumbbell Romanian deadlift':['Dumbbells','Per dumbbell'],
 'Reverse lunge':['Dumbbells or bodyweight','Per dumbbell'],
 'Standing calf raise':['Wall or rack for balance',null],
 'Forearm plank':['Exercise mat',null],
 'Brisk treadmill walk':['Treadmill',null],
 'Standing hip flexor stretch':['Open floor space',null],
 'Standing chest opener':['Open floor space',null],
 'Incline dumbbell press':['Incline bench + dumbbells','Per dumbbell'],
 'Single-arm dumbbell row':['Bench + one dumbbell','Dumbbell weight'],
 'Dumbbell lateral raise':['Dumbbells','Per dumbbell'],
 'Cable triceps pushdown':['High pulley + straight cable bar','Selected stack weight'],
 'Dumbbell hammer curl':['Dumbbells','Per dumbbell'],
 'Glute bridge':['Exercise mat',null],
 'Dead bug':['Exercise mat',null],
 'Brisk outdoor or treadmill walk':['Treadmill or outdoor route',null],
 'Bodyweight squat':['Open floor space',null],
 'Optional easy walk':['Comfortable walking route',null],
 'Gentle standing side stretch':['Open floor space',null]
};
for(const routine of foundationRoutines)for(const exercise of routine.exercises){const [equipment,loadHint]=equipmentByName[exercise.name];Object.assign(exercise,{equipment,loadHint,weighted:!!loadHint});}
const g=(name,sets,reps,rest,type,muscles,cues,equipment,setup,loadHint='Selected stack weight')=>({...e(name,sets,reps,rest,type,muscles,cues),equipment,setup,loadHint,weighted:true});
const bench=g('Barbell bench press',3,'6–10',120,'bench','Chest · triceps',['Plant both feet; grip the bar evenly with wrists over elbows.','Lower the bar toward your mid-chest with control; do not bounce.','Press back up smoothly. Use a spotter or correctly set rack safeties.'],'Flat bench + barbell rack','Set the rack so you can unrack without losing shoulder position. Set safety bars just below your chest position, or ask for a spotter.','Total bar + plates');
const cableRow=g('Seated cable row',3,'10–12',90,'row','Back · biceps',['Sit tall with a neutral spine and softly bent knees.','Pull the close-grip handle toward your lower ribs without leaning back.','Return slowly; keep the cable under control.'],'Low cable row station + close-grip handle','Attach the handle, secure the weight pin, and place your feet firmly on the platforms.');
const shoulder=g('Machine shoulder press',2,'10–12',90,'press','Shoulders · triceps',['Keep your back supported, feet planted, and abdomen braced.','Press upward without shrugging or locking elbows hard.','Lower slowly to a comfortable shoulder position.'],'Seated shoulder-press machine','Adjust the seat so the handles begin around shoulder height. Choose a light pin setting for your first practice set.');
const pulldown=g('Lat pulldown',3,'10–12',90,'pull','Back · biceps',['Keep your chest tall with only a slight backward lean.','Pull the bar toward your upper chest; do not pull behind your neck.','Let your arms extend with control without swinging.'],'High pulley + wide pulldown bar','Secure the weight pin and adjust the thigh pad to hold your legs comfortably.');
const cableCurl=g('Cable biceps curl',2,'10–15',60,'curl','Biceps',['Stand tall and keep your upper arms near your sides.','Curl the bar without swinging your torso or moving your elbows forward.','Lower slowly and keep wrists comfortable.'],'Low pulley + straight or EZ cable bar','Set the pulley low, clip on the bar, and stand far enough back to keep light cable tension.');
const triceps=g('Rope triceps pushdown',2,'10–15',60,'pushdown','Triceps',['Keep elbows tucked beside your ribs and shoulders relaxed.','Straighten your elbows and gently separate the rope ends at the bottom.','Return with control; keep your upper arms still.'],'High pulley + rope attachment','Clip the rope to a high pulley and secure the weight pin. Use a stable stance with softly bent knees.');
const legPress=g('45° leg press',3,'10–12',120,'squat','Quads · glutes',['Keep your head, back, and hips against the pads; place feet around shoulder width.','Lower only as far as you can keep your hips and lower back against the pad.','Press smoothly without locking your knees; re-engage the catches before getting out.'],'Plate-loaded 45° leg-press machine','Find the safety catches before starting and set a comfortable seat position. Start with a light sled load and add plates evenly.','Added plates, both sides');
const legCurl=g('Seated leg curl',3,'10–15',75,'hinge','Hamstrings',['Keep your thighs secured and hips against the seat.','Curl your heels underneath you through a comfortable range.','Return slowly without letting the stack slam.'],'Seated leg-curl machine','Align your knees with the machine pivot. Set the lower pad just above your heels and the thigh pad snugly.');
const extension=g('Leg extension',2,'12–15',60,'squat','Quads',['Keep your back against the seat and hold the handles lightly.','Straighten your knees smoothly through a comfortable range.','Lower slowly without kicking or dropping the weight stack.'],'Leg-extension machine','Align your knees with the pivot and place the roller just above your ankles. Adjust the backrest before choosing the pin weight.');
const calves=g('Standing calf raise machine',3,'12–15',60,'calf','Calves',['Place the balls of your feet securely on the platform and keep knees softly straight.','Rise onto your toes without bouncing, then pause.','Lower heels slowly through a comfortable range while holding the handles.'],'Standing calf-raise machine','Adjust the shoulder pads so you can stand tall. Learn the release and stop mechanism before loading.');
const machineRow=g('Chest-supported machine row',3,'10–12',90,'row','Back · biceps',['Keep your chest against the pad and feet stable.','Pull the handles toward your ribs without lifting your chest away.','Return slowly with shoulders relaxed and no jerking.'],'Chest-supported row machine','Adjust the seat so the handles are near your lower chest. Use the chest pad for support throughout the set.');
const pecDeck=g('Pec deck chest fly',2,'12–15',60,'raise','Chest',['Keep your back supported with a soft bend in your elbows.','Bring the handles together in front of your chest without shrugging.','Open slowly only as far as your shoulders feel comfortable.'],'Pec deck / chest-fly machine','Set the seat so the handles are around chest height. Set the starting position conservatively rather than far behind your body.');
const smith=g('Smith machine squat',3,'8–12',120,'squat','Quads · glutes',['Rest the bar across your upper back, not your neck, and brace your abdomen.','Squat through a comfortable depth with heels planted and knees tracking over toes.','Stand smoothly, then rotate the bar back onto its hooks before stepping away.'],'Smith machine','Set the safety stops just below your chosen squat depth. Practice the hook release and rerack with a very light bar first.','Added plates, both sides');
const abduction=g('Hip abduction machine',2,'12–15',60,'lunge','Outer glutes',['Sit tall with your back supported and feet on the supports.','Open your knees outward with control without rocking your torso.','Bring the pads back together slowly; avoid letting the stack slam.'],'Seated hip-abduction machine','Use the machine configured to push your knees outward. Set the starting width comfortably and choose a light pin weight.');
const pallof=g('Cable Pallof press',2,'10 / side',60,'press','Core · anti-rotation',['Stand sideways to the cable with feet planted and hands at your chest.','Press your hands straight forward while resisting the pull to rotate.','Return slowly and repeat on the other side; keep breathing.'],'Cable station + single handle','Set the pulley around chest height and start with a light load. Position yourself so the cable pulls from your side.');
const fromBase=(day,name)=>foundationRoutines[day].exercises.find(e=>e.name===name);
export const routines=[
 {...foundationRoutines[0],title:'Press, pull, build.',description:'Put the gym to work. Barbell basics, cables, and supported presses.',time:55,exercises:[bench,cableRow,shoulder,pulldown,cableCurl,triceps]},
 {...foundationRoutines[1],title:'Leg day, made purposeful.',description:'Use the leg machines for controlled strength through a comfortable range.',time:45,exercises:[legPress,legCurl,extension,calves,fromBase(1,'Forearm plank')]},
 foundationRoutines[2],
 {...foundationRoutines[3],title:'A stronger kind of balance',description:'Incline presses, a supported row, and focused cable work.',time:50,exercises:[fromBase(3,'Incline dumbbell press'),machineRow,pecDeck,fromBase(3,'Dumbbell lateral raise'),triceps,fromBase(3,'Dumbbell hammer curl')]},
 {...foundationRoutines[4],title:'Build your lower-body engine',description:'Train your squat and hinge, then finish with machine and cable control.',time:50,exercises:[smith,fromBase(4,'Dumbbell Romanian deadlift'),legCurl,abduction,pallof]},
 foundationRoutines[5],foundationRoutines[6]
];
export const plans={gym:{label:'Full gym',routines},foundation:{label:'Dumbbells + cables',routines:foundationRoutines}};
export const isSessionKey=key=>/^\d{4}-\d{2}-\d{2}:[0-6](?::gym-v1)?$/.test(key);
export const planForSession=key=>key.endsWith(':gym-v1')?'gym':'foundation';
export const routineForSession=key=>plans[planForSession(key)].routines[Number(key.split(':')[1])];

export function weekKey(date=new Date()){const d=new Date(date.getFullYear(),date.getMonth(),date.getDate());d.setDate(d.getDate()-(d.getDay()+6)%7);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function sessionKey(day,date=new Date(),plan='gym'){return `${weekKey(date)}:${day}${plan==='gym'?':gym-v1':''}`;}
