import test from 'node:test';
import assert from 'node:assert/strict';
import {routines,foundationRoutines,homeRoutines} from '../routines.js';
import {demos,demoFor,embedUrl,thumbnail,videoGuide} from '../media.js';
import {readFileSync} from 'node:fs';
test('every exercise has its own verified real demonstration, including shared visual types',()=>{const exercises=[...routines,...foundationRoutines,...homeRoutines].flatMap(r=>r.exercises);assert.equal(Object.keys(demos).length,41);for(const exercise of exercises){const demo=demoFor(exercise);assert.match(demo.id,/^[\w-]{11}$/);assert.ok(demo.author);assert.ok(demo.title);assert.equal(demo.end-demo.start,30);assert.match(demo.source,/^https:\/\/www.youtube.com\/watch\?v=/);}assert.ok(demoFor({name:'Knee push-ups'}));assert.notEqual(demos['Goblet squat'].id,demos['Bodyweight squat'].id);assert.notEqual(demos['Dumbbell curl'].id,demos['Dumbbell hammer curl'].id);assert.notEqual(demos['Standing chest opener'].id,demos['Gentle standing side stretch'].id);});
test('iPhone embed has inline playback, short duration, mute, and proper referrer policy',()=>{const e=foundationRoutines[0].exercises[0];const url=new URL(embedUrl(demoFor(e),'https://raymondotoo.github.io'));assert.equal(url.hostname,'www.youtube-nocookie.com');assert.equal(url.searchParams.get('playsinline'),'1');assert.equal(url.searchParams.get('end'),'30');assert.equal(url.searchParams.get('mute'),'1');assert.equal(url.searchParams.get('origin'),'https://raymondotoo.github.io');const html=videoGuide(e,true);assert.match(html,/referrerpolicy="strict-origin-when-cross-origin"/);assert.match(html,/Watch full video/);assert.match(html,/Muscle &amp; Strength/);assert.match(thumbnail(e,0),/data-detail="0"/);});
test('offline movement guides retain actionable cues without loading a player',()=>{const html=videoGuide(routines[0].exercises[0],false);assert.doesNotMatch(html,/<iframe/);assert.match(html,/You’re offline/);assert.match(html,/form cues and set tracking/);});
test('media registry ships in offline cache and Pages artifact',()=>{assert.match(readFileSync('sw.js','utf8'),/'\.\/media.js'/);assert.match(readFileSync('.github/workflows/pages.yml','utf8'),/cp .*media.js/);assert.match(readFileSync('app.js','utf8'),/addEventListener\('close'/);});
